---
AWSTemplateFormatVersion: "2010-09-09"

Description: Incrementally building a cloudformation template

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      # Add tags to our VPC
      Tags:
        - Key: Name
          Value: !Ref "AWS::StackName"
